[package]
name = "verification-licences"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.12", features = ["cookies", "blocking"] }
log = "0.4.26"
env_logger = { version = "0.11.6", features = [] }
