[package]
name = "verification-licences"
version = "0.1.0"
edition = "2024"

[dependencies]
# Logs
log = "0.4.26"
env_logger = { version = "0.11.6", features = [] }

# Web
reqwest = { version = "0.12.12", features = ["cookies"] }
 rocket = "0.5.1"

# Utils
regex = "1.11.1"
chrono = "0.4.39"
csv = "1.3.1"
encoding = "0.2.33"
serde = { version = "1.0.218", features = ["derive"] }
derive-getters = "0.5.0"
parameterized = "2.0.0"